name: invtex
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - gcc=11.2.0=h702ea55_10
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=12.1.0=ha89aaad_17
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - brotli==1.2.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - dataclasses-json==0.6.7
      - datasets==4.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diffusers==0.36.0
      - dill==0.4.0
      - easydict==1.13
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.124.4
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.13.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - glcontext==3.0.0
      - gputil==1.4.0
      - gradio==6.1.0
      - gradio-client==2.0.1
      - gradio-imageslider==0.0.20
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - igraph==0.11.9
      - imageio==2.34.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - ipykernel==7.0.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - kornia==0.7.2
      - kornia-rs==0.1.9
      - lark==1.3.0
      - lazy-loader==0.4
      - llvmlite==0.45.1
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - moderngl==5.12.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==2.8.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.7.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==2.2.6
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - objaverse==0.1.7
      - onnxruntime==1.23.1
      - open3d==0.17.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - plyfile==1.1.2
      - pooch==1.8.2
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygltflib==1.16.5
      - pygments==2.19.2
      - pymatting==1.1.14
      - pymeshfix==0.17.1
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pyvista==0.46.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.9.18
      - rembg==2.0.67
      - requests==2.32.5
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scooby==0.10.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - setuptools==80.9.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.13.1
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - trimesh==4.4.0
      - triton==3.1.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - types-python-dateutil==2.9.0.20251008
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - utils3d==0.0.2
      - uvicorn==0.38.0
      - vtk==9.5.2
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xatlas==0.0.11
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/cjh/miniconda3/envs/invtex
